<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\Common\PlanWise.Common.Presentation\PlanWise.Common.Presentation.csproj" />
    <ProjectReference Include="..\PlanWise.Modules.CostEstimation.Application\PlanWise.Modules.CostEstimation.Application.csproj" />
  </ItemGroup>

</Project>
