<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\..\..\Common\PlanWise.Common.Presentation\PlanWise.Common.Presentation.csproj" />
		<ProjectReference Include="..\PlanWise.Modules.IdentityAccess.Application\PlanWise.Modules.IdentityAccess.Application.csproj" />
  </ItemGroup>

</Project>
