<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\PlanWise.Common.Domain\PlanWise.Common.Domain.csproj" />
    <ProjectReference Include="..\PlanWise.Common.Application\PlanWise.Common.Application.csproj" />
  </ItemGroup>

</Project>
