// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanWise.Modules.Scheduling.Infrastructure.Database;

#nullable disable

namespace PlanWise.Modules.Scheduling.Infrastructure.Database.Migrations;

[DbContext(typeof(SchedulingDbContext))]
partial class SchedulingDbContextModelSnapshot : ModelSnapshot
{
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanWise.Modules.Scheduling.Domain.Milestones.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_milestones_project_id");

                    b.ToTable("milestones", "scheduling");
                });

            modelBuilder.Entity("PlanWise.Modules.Scheduling.Domain.Optimisation.ProposedAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_assignee_id");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<string>("ProposedAssigneeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("proposed_assignee_email");

                    b.Property<Guid>("ProposedAssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_assignee_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("task_key");

                    b.HasKey("Id")
                        .HasName("pk_proposed_assignment");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("ix_proposed_assignment_proposal_id");

                    b.ToTable("proposed_assignment", "scheduling");
                });

            modelBuilder.Entity("PlanWise.Modules.Scheduling.Domain.Optimisation.ScheduleProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("ConstraintsHonoured")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("constraints_honoured");

                    b.PrimitiveCollection<string[]>("ConstraintsRelaxed")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("constraints_relaxed");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExpectedGain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("expected_gain");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("objective");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_schedule_proposals");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_schedule_proposals_project_id");

                    b.ToTable("schedule_proposals", "scheduling");
                });

            modelBuilder.Entity("PlanWise.Modules.Scheduling.Domain.Schedule.ScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_items");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_schedule_items_project_id");

                    b.ToTable("schedule_items", "scheduling");
                });

            modelBuilder.Entity("PlanWise.Modules.Scheduling.Domain.Optimisation.ProposedAssignment", b =>
                {
                    b.HasOne("PlanWise.Modules.Scheduling.Domain.Optimisation.ScheduleProposal", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposed_assignment_schedule_proposals_proposal_id");
                });

            modelBuilder.Entity("PlanWise.Modules.Scheduling.Domain.Optimisation.ScheduleProposal", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
}
