// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanWise.Modules.WorkspaceManagement.Infrastructure.Database;

#nullable disable

namespace PlanWise.Modules.WorkspaceManagement.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WorkspaceManagementDbContext))]
    partial class WorkspaceManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workspace_management")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanWise.Modules.WorkspaceManagement.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("process");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_key_prefix");

                    b.ToTable("projects", "workspace_management");
                });

            modelBuilder.Entity("PlanWise.Modules.WorkspaceManagement.Domain.Projects.ProjectLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("ProjectId1")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id1");

                    b.HasKey("Id")
                        .HasName("pk_project_labels");

                    b.HasIndex("ProjectId1")
                        .HasDatabaseName("ix_project_labels_project_id1");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_labels_project_id_name");

                    b.ToTable("project_labels", "workspace_management");
                });

            modelBuilder.Entity("PlanWise.Modules.WorkspaceManagement.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("capacity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("ProjectId1")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id1");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("ProjectId1")
                        .HasDatabaseName("ix_project_members_project_id1");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_members_project_id_user_id");

                    b.ToTable("project_members", "workspace_management");
                });

            modelBuilder.Entity("PlanWise.Modules.WorkspaceManagement.Domain.Projects.ProjectLabel", b =>
                {
                    b.HasOne("PlanWise.Modules.WorkspaceManagement.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_labels_projects_project_id");

                    b.HasOne("PlanWise.Modules.WorkspaceManagement.Domain.Projects.Project", null)
                        .WithMany("Labels")
                        .HasForeignKey("ProjectId1")
                        .HasConstraintName("fk_project_labels_projects_project_id1");
                });

            modelBuilder.Entity("PlanWise.Modules.WorkspaceManagement.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("PlanWise.Modules.WorkspaceManagement.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("PlanWise.Modules.WorkspaceManagement.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId1")
                        .HasConstraintName("fk_project_members_projects_project_id1");
                });

            modelBuilder.Entity("PlanWise.Modules.WorkspaceManagement.Domain.Projects.Project", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
