<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\PlanWise.Common.Infrastructure\PlanWise.Common.Infrastructure.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlanWise.Modules.WorkspaceManagement.Application\PlanWise.Modules.WorkspaceManagement.Application.csproj" />
    <ProjectReference Include="..\PlanWise.Modules.WorkspaceManagement.Presentation\PlanWise.Modules.WorkspaceManagement.Presentation.csproj" />
  </ItemGroup>

</Project>