<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>beeb096e-b519-4311-9b85-dd70aed621f6</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\IdentityAccess\PlanWise.Modules.IdentityAccess.Infrastructure\PlanWise.Modules.IdentityAccess.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\WorkspaceManagement\PlanWise.Modules.WorkspaceManagement.Infrastructure\PlanWise.Modules.WorkspaceManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Delivery\PlanWise.Modules.Delivery.Infrastructure\PlanWise.Modules.Delivery.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Scheduling\PlanWise.Modules.Scheduling.Infrastructure\PlanWise.Modules.Scheduling.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\CostEstimation\PlanWise.Modules.CostEstimation.Infrastructure\PlanWise.Modules.CostEstimation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\RiskPrediction\PlanWise.Modules.RiskPrediction.Infrastructure\PlanWise.Modules.RiskPrediction.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\BacklogPrioritisation\PlanWise.Modules.BacklogPrioritisation.Infrastructure\PlanWise.Modules.BacklogPrioritisation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\PlanWise.Modules.Notifications.Infrastructure\PlanWise.Modules.Notifications.Infrastructure.csproj" />
  </ItemGroup>

</Project>
