using PlanWise.Modules.RiskPrediction.Application.Abstractions;
using PlanWise.Modules.RiskPrediction.Application.Risks;

namespace PlanWise.Modules.RiskPrediction.Application.Tests;

/// <summary>
/// Pins the served model to the exported artifact.
///
/// The artifact is a specification, not just a bag of weights: impute the median, clamp at zero,
/// log1p, standardise, weight, sum, Platt-scale. That specification now has two independent
/// implementations — Python in research/sprint-slip-model and C# in TrainedSlipScorer — and nothing
/// but this test stops them drifting apart. Drift here would not throw or fail a build; it would
/// quietly serve different probabilities than the ones that were evaluated.
/// </summary>
public sealed class TrainedSlipScorerTests
{
    private static readonly SlipModelArtifact Model = SlipModelArtifact.Instance;

    private static readonly string[] FeatureOrder =
    [
        "story_point", "blocking_links", "sprint_issue_count", "sprint_story_points", "sprint_length_days"
    ];

    // Expected values are generated by research/sprint-slip-model/golden_cases.py and must be
    // regenerated whenever the artifact is. Each row supplies story points, then blocking links,
    // then the sprint's task count, its committed points and its length in days, and finally the
    // probability the Python reference produced. An absent value means the caller could not supply
    // that feature, in which case the model's training median stands in for it.
    [Theory]
    [InlineData(2d, 0d, 19d, 23d, 11d, 0.4186912376)]              // real row 0
    [InlineData(5d, 0d, 27d, 136d, 12d, 0.3723348221)]             // real row 3208
    [InlineData(8d, 0d, 14d, 82d, 12d, 0.4292149503)]              // real row 6416
    [InlineData(5d, 0d, 2d, 10d, 14d, 0.4851043408)]               // real row 9624
    [InlineData(4d, 0d, 4d, 28d, 14d, 0.4097940579)]               // real row 12832
    [InlineData(1d, 2d, 30d, 119.5d, 28d, 0.4760330227)]           // real row 16040
    [InlineData(null, null, null, null, null, 0.3706792703)]  // no estimate, no sprint
    [InlineData(null, 0d, 20d, 60d, 14d, 0.3826728533)]           // unestimated task in a real sprint
    [InlineData(8d, 2d, 5d, 13d, 14d, 0.7196140322)]               // two blockers, small sprint
    [InlineData(3d, 0d, 10d, 30d, -5d, 0.3767539538)]              // end date before start date
    [InlineData(0d, 0d, 0d, 0d, 0d, 0.4058476415)]                 // all zero
    public void ScoreVector_matches_the_python_reference_implementation(
        double? storyPoints, double? blockingLinks, double? sprintIssues,
        double? sprintPoints, double? sprintLength, double expected)
    {
        TrainedSlipScorer.Scored scored = TrainedSlipScorer.ScoreVector(
            Model, Vector(storyPoints, blockingLinks, sprintIssues, sprintPoints, sprintLength));

        Assert.Equal(expected, (double)scored.Probability, precision: 8);
    }

    [Fact]
    public void Contributions_sum_to_the_logit_so_the_explanation_is_the_actual_reasoning()
    {
        TrainedSlipScorer.Scored scored = TrainedSlipScorer.ScoreVector(Model, Vector(8, 2, 5, 13, 14));

        double summed = Model.Intercept + scored.Contributions.Sum(feature => (double)feature.Weight);

        // Contributions are rounded for display, hence the tolerance rather than exact equality.
        Assert.Equal(scored.Logit, summed, precision: 3);
    }

    [Fact]
    public void A_blocked_task_scores_higher_than_the_same_task_unblocked()
    {
        // The single strongest signal in the study: two blocking links took the slip rate from 39%
        // to 68%. If the sign of that relationship ever inverts, the model is wired up wrong.
        decimal unblocked = TrainedSlipScorer.ScoreVector(Model, Vector(5, 0, 20, 60, 14)).Probability;
        decimal blocked = TrainedSlipScorer.ScoreVector(Model, Vector(5, 2, 20, 60, 14)).Probability;

        Assert.True(blocked > unblocked, $"blocked {blocked} should exceed unblocked {unblocked}");
    }

    [Fact]
    public void An_unavailable_feature_is_reported_as_imputed_rather_than_passed_off_as_known()
    {
        TrainedSlipScorer.Scored scored = TrainedSlipScorer.ScoreVector(Model, Vector(null, 0, 20, 60, 14));

        RiskFeatureContribution points =
            scored.Contributions.Single(feature => feature.Feature == "story_point");

        Assert.Contains("training median", points.Detail, StringComparison.Ordinal);
    }

    [Fact]
    public void Every_probability_is_a_probability()
    {
        // Platt scaling cannot leave [0,1], but the clamp and the decimal conversion could; absurd
        // inputs are the cheapest way to find out.
        foreach (double magnitude in new[] { 0d, 1d, 1_000d, 1_000_000d })
        {
            decimal probability = TrainedSlipScorer
                .ScoreVector(Model, Vector(magnitude, magnitude, magnitude, magnitude, magnitude))
                .Probability;

            Assert.InRange(probability, 0m, 1m);
        }
    }

    [Fact]
    public void The_embedded_artifact_is_the_one_that_was_evaluated()
    {
        Assert.Equal(1, Model.SchemaVersion);
        Assert.Equal("log1p", Model.Transform);
        Assert.Equal(19_251, Model.Provenance.Rows);
        Assert.Equal(36, Model.Provenance.Projects);
        Assert.Equal(FeatureOrder, Model.Features.Select(feature => feature.Name));

        // A zero scale would divide by zero; a zero-length feature list would make every task
        // identical. Both would be silent.
        Assert.All(Model.Features, feature => Assert.NotEqual(0.0, feature.Scale));
    }

    private static Dictionary<string, double?> Vector(
        double? storyPoints, double? blockingLinks, double? sprintIssues,
        double? sprintPoints, double? sprintLength) =>
        new(StringComparer.Ordinal)
        {
            ["story_point"] = storyPoints,
            ["blocking_links"] = blockingLinks,
            ["sprint_issue_count"] = sprintIssues,
            ["sprint_story_points"] = sprintPoints,
            ["sprint_length_days"] = sprintLength,
        };
}
