// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanWise.Modules.BacklogPrioritisation.Infrastructure.Database;

#nullable disable

namespace PlanWise.Modules.BacklogPrioritisation.Infrastructure.Database.Migrations;

[DbContext(typeof(BacklogPrioritisationDbContext))]
partial class BacklogPrioritisationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("backlog_prioritisation")
            .HasAnnotation("ProductVersion", "9.0.16")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("PlanWise.Modules.BacklogPrioritisation.Domain.Priorities.PriorityItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<decimal>("ComplexityScore")
                    .HasColumnType("numeric")
                    .HasColumnName("complexity_score");

                b.Property<int>("CurrentPosition")
                    .HasColumnType("integer")
                    .HasColumnName("current_position");

                b.Property<decimal>("DependencyScore")
                    .HasColumnType("numeric")
                    .HasColumnName("dependency_score");

                b.Property<int>("ProposedPosition")
                    .HasColumnType("integer")
                    .HasColumnName("proposed_position");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("reason");

                b.Property<decimal>("RiskScore")
                    .HasColumnType("numeric")
                    .HasColumnName("risk_score");

                b.Property<Guid>("RunId")
                    .HasColumnType("uuid")
                    .HasColumnName("run_id");

                b.Property<Guid>("TaskId")
                    .HasColumnType("uuid")
                    .HasColumnName("task_id");

                b.Property<string>("TaskKey")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("task_key");

                b.Property<decimal>("ValueScore")
                    .HasColumnType("numeric")
                    .HasColumnName("value_score");

                b.HasKey("Id")
                    .HasName("pk_priority_item");

                b.HasIndex("RunId")
                    .HasDatabaseName("ix_priority_item_run_id");

                b.ToTable("priority_item", "backlog_prioritisation");
            });

        modelBuilder.Entity("PlanWise.Modules.BacklogPrioritisation.Domain.Priorities.PriorityRun", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("AppliedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("applied_at_utc");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<DateTime?>("DismissedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("dismissed_at_utc");

                b.Property<string>("DismissedReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("dismissed_reason");

                b.Property<Guid>("JobId")
                    .HasColumnType("uuid")
                    .HasColumnName("job_id");

                b.Property<string>("ModelVersion")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("model_version");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("project_id");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.HasKey("Id")
                    .HasName("pk_priority_runs");

                b.HasIndex("ProjectId")
                    .HasDatabaseName("ix_priority_runs_project_id");

                b.ToTable("priority_runs", "backlog_prioritisation");
            });

        modelBuilder.Entity("PlanWise.Modules.BacklogPrioritisation.Domain.Priorities.PriorityItem", b =>
            {
                b.HasOne("PlanWise.Modules.BacklogPrioritisation.Domain.Priorities.PriorityRun", null)
                    .WithMany("Items")
                    .HasForeignKey("RunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_priority_item_priority_runs_run_id");
            });

        modelBuilder.Entity("PlanWise.Modules.BacklogPrioritisation.Domain.Priorities.PriorityRun", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
    }
}
