"""Emit C# assertions that pin the served model to this artifact.

The exported JSON is a specification, not just weights: it says impute the median, clamp at zero,
log1p, standardise, weight, sum, then Platt. Two independent implementations of that spec now exist
-- Python here and C# in TrainedSlipScorer -- and nothing stops them drifting apart except a test
that runs the same vectors through both.

This prints the expected side of that test. Real rows from the training data cover the ordinary
case; the hand-written vectors cover the edges that only ever occur in production: a task with no
estimate, a sprint whose end precedes its start, a task in no sprint at all.

Run when the artifact is regenerated, and paste the output over the table in the C# test.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pandas as pd

ARTIFACT = Path("sprint-slip-model.json")
DATA = Path("dataset.parquet")


def score(model: dict, values: dict[str, float | None]) -> float:
    """The artifact's documented maths, implemented straight from the JSON."""
    logit = model["intercept"]
    for feature in model["features"]:
        raw = values[feature["name"]]
        value = feature["median"] if raw is None else raw
        standardised = (math.log1p(max(0.0, value)) - feature["mean"]) / feature["scale"]
        logit += feature["coefficient"] * standardised

    calibration = model["calibration"]
    return 1.0 / (1.0 + math.exp(calibration["a"] * logit + calibration["b"]))


def main() -> int:
    model = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    names = [feature["name"] for feature in model["features"]]

    frame = pd.read_parquet(DATA)
    # Spread across the range rather than taking the head, which would be one project's sprint.
    sample = frame.iloc[:: max(1, len(frame) // 6)].head(6)

    cases: list[tuple[str, dict[str, float | None]]] = [
        (f"real row {index}", {name: float(row[name]) for name in names})
        for index, row in sample.iterrows()
    ]
    cases += [
        ("no estimate, no sprint", dict.fromkeys(names)),
        ("unestimated task in a real sprint", {
            "story_point": None, "blocking_links": 0.0, "sprint_issue_count": 20.0,
            "sprint_story_points": 60.0, "sprint_length_days": 14.0}),
        ("two blockers, small sprint", {
            "story_point": 8.0, "blocking_links": 2.0, "sprint_issue_count": 5.0,
            "sprint_story_points": 13.0, "sprint_length_days": 14.0}),
        ("end date before start date", {
            "story_point": 3.0, "blocking_links": 0.0, "sprint_issue_count": 10.0,
            "sprint_story_points": 30.0, "sprint_length_days": -5.0}),
        ("all zero", dict.fromkeys(names, 0.0)),
    ]

    print("        // Generated by research/sprint-slip-model/golden_cases.py -- regenerate when the")
    print("        // artifact changes. Order: story points, blocking links, sprint tasks, sprint")
    print("        // points, sprint length; null means the value is unavailable to the caller.")
    for label, values in cases:
        # The "d" suffix matters: xUnit will not convert an int literal to a double? parameter.
        cells = ", ".join("null" if values[name] is None else f"{values[name]:g}d" for name in names)
        print(f"        [InlineData({cells}, {score(model, values):.10f})]  // {label}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
