// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanWise.Modules.RiskPrediction.Infrastructure.Database;

#nullable disable

namespace PlanWise.Modules.RiskPrediction.Infrastructure.Database.Migrations;

[DbContext(typeof(RiskPredictionDbContext))]
[Migration("20260823170757_CreateRiskPrediction")]
partial class CreateRiskPrediction
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("risk_prediction")
            .HasAnnotation("ProductVersion", "9.0.16")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("PlanWise.Modules.RiskPrediction.Domain.Risks.RiskAssessmentRun", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.PrimitiveCollection<string[]>("Assumptions")
                    .IsRequired()
                    .HasColumnType("text[]")
                    .HasColumnName("assumptions");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<Guid>("JobId")
                    .HasColumnType("uuid")
                    .HasColumnName("job_id");

                b.Property<string>("ModelVersion")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("model_version");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("project_id");

                b.Property<int>("TrainingWindowDays")
                    .HasColumnType("integer")
                    .HasColumnName("training_window_days");

                b.HasKey("Id")
                    .HasName("pk_risk_assessment_runs");

                b.HasIndex("ProjectId")
                    .HasDatabaseName("ix_risk_assessment_runs_project_id");

                b.ToTable("risk_assessment_runs", "risk_prediction");
            });

        modelBuilder.Entity("PlanWise.Modules.RiskPrediction.Domain.Risks.SprintForecast", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<decimal>("CompletionProbability")
                    .HasColumnType("numeric")
                    .HasColumnName("completion_probability");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<decimal>("ExpectedPoints")
                    .HasColumnType("numeric")
                    .HasColumnName("expected_points");

                b.Property<DateOnly>("P50DeliveryDate")
                    .HasColumnType("date")
                    .HasColumnName("p50delivery_date");

                b.Property<DateOnly>("P90DeliveryDate")
                    .HasColumnType("date")
                    .HasColumnName("p90delivery_date");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("project_id");

                b.Property<Guid>("RunId")
                    .HasColumnType("uuid")
                    .HasColumnName("run_id");

                b.Property<Guid>("SprintId")
                    .HasColumnType("uuid")
                    .HasColumnName("sprint_id");

                b.HasKey("Id")
                    .HasName("pk_sprint_forecasts");

                b.HasIndex("ProjectId")
                    .HasDatabaseName("ix_sprint_forecasts_project_id");

                b.HasIndex("RunId")
                    .HasDatabaseName("ix_sprint_forecasts_run_id");

                b.HasIndex("SprintId")
                    .HasDatabaseName("ix_sprint_forecasts_sprint_id");

                b.ToTable("sprint_forecasts", "risk_prediction");
            });

        modelBuilder.Entity("PlanWise.Modules.RiskPrediction.Domain.Risks.TaskRiskAssessment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<int>("DayImpact")
                    .HasColumnType("integer")
                    .HasColumnName("day_impact");

                b.Property<bool>("Dismissed")
                    .HasColumnType("boolean")
                    .HasColumnName("dismissed");

                b.Property<DateTime?>("DismissedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("dismissed_at_utc");

                b.Property<string>("DismissedReason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("dismissed_reason");

                b.Property<string>("FeatureContributionsJson")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("feature_contributions_json");

                b.Property<decimal>("ProbabilityOfSlip")
                    .HasColumnType("numeric")
                    .HasColumnName("probability_of_slip");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("project_id");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("reason");

                b.Property<Guid>("RunId")
                    .HasColumnType("uuid")
                    .HasColumnName("run_id");

                b.Property<Guid>("TaskId")
                    .HasColumnType("uuid")
                    .HasColumnName("task_id");

                b.Property<string>("TaskKey")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("task_key");

                b.HasKey("Id")
                    .HasName("pk_task_risk_assessments");

                b.HasIndex("ProjectId")
                    .HasDatabaseName("ix_task_risk_assessments_project_id");

                b.HasIndex("RunId")
                    .HasDatabaseName("ix_task_risk_assessments_run_id");

                b.HasIndex("TaskId")
                    .HasDatabaseName("ix_task_risk_assessments_task_id");

                b.ToTable("task_risk_assessments", "risk_prediction");
            });
#pragma warning restore 612, 618
    }
}
