// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanWise.Modules.Delivery.Infrastructure.Database;

#nullable disable

namespace PlanWise.Modules.Delivery.Infrastructure.Database.Migrations;

[DbContext(typeof(DeliveryDbContext))]
[Migration("20260822110709_CreateDelivery")]
partial class CreateDelivery
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("delivery")
            .HasAnnotation("ProductVersion", "9.0.16")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("PlanWise.Modules.Delivery.Domain.Sprints.Sprint", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateOnly>("EndDate")
                    .HasColumnType("date")
                    .HasColumnName("end_date");

                b.Property<string>("Goal")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("goal");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("project_id");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("date")
                    .HasColumnName("start_date");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("state");

                b.HasKey("Id")
                    .HasName("pk_sprints");

                b.HasIndex("ProjectId")
                    .HasDatabaseName("ix_sprints_project_id");

                b.ToTable("sprints", "delivery");
            });
#pragma warning restore 612, 618
    }
}
